name: Documentation

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Deploy Documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Setup Rust
    